### ISSUE TITLE
Pressing the close (cross) button of the GUI causes freeze of the whole program

### ISSUE THREAD

**Issue by tschodde** [jpoeppel/ipaacaPlot#12]
Pressing the close (cross) button of the GUI causes freeze of the whole program. This seems to happen only in Windows. (testet on Windows 10 x64 1607 with wx 3.0.2.0)

**Comment by jpoeppel** [comment]
It looks like the culprint is rsb as also mentioned on their repo: https://code.cor-lab.org/issues/1463.

Will have to look into that more in order to find out what processes/threads are created and how I can kill them.

**Comment by jpoeppel** [comment]
Removing all listeners in the inputBuffer seems to work from those. However the outputBuffer also holds some lingering feelings we'll have to track down and remove!

**Comment by jpoeppel** [comment]
I'll close this for now. If the current solution introduces other bugs they should be their own issues.
